name: Belowthefog
favicon: null
layout_spectrum: 0.24074
typography_spectrum: 0.5
title: Digital Creative Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#b3b3b3'
    - '#7a7a7a'
    - '#4d4d4d'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
