name: Belowthefog
favicon: null
layout_spectrum: 0.21495782118290663
typography_spectrum: 0.7134131286293268
title: Digital Creative Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.27211065986193717
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
